version: '3.9'
services:
  database:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cuckoo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
      - /server/vendor/bundle
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres@database:5432/cuckoo
    command: bundle exec rails s -p 8000
  client:
    container_name: client
    image: 'node:16-alpine'
    user: 'node'
    working_dir: /cuckoo/client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/cuckoo/client
    command: bash -c "yarn && yarn start"
    depends_on:
      - server
