Type.create(name: 'Announcement',slack_channel: '#test')
Type.create(name: 'Event',slack_channel: '#test')
Company.create(name: 'Assure Hedge', description: 'Assure Hedge offers reliable currency hedging solutions to FX brokers, banks and payment entities which easily integrates into their product suite', status: 'a ver', logo:'kappa')
Company.create(name: 'Bloco', description: 'We are a small and independent studio specialised in designing and developing Android products.', status: 'a ver', logo:'kappa')
Company.create(name: 'Deemaze', description: 'Software agency building digital products and services.', status: 'a ver', logo:'kappa')
Company.create(name: 'Fidizzi', description: 'We deliver full-cycle Salesforce professional services to help organisations embrace the world’s leading CRM platform.', status: 'a ver', logo:'kappa')
Company.create(name: 'Fucking Amazing', description: 'Para nós o marketing e a comunicação não têm tabus, ou então não seríamos Fucking Amazing!', status: 'a ver', logo:'kappa')
Company.create(name: 'Good Barber', description: 'GoodBarber is an App Builder. A no-code platform to make high-performing native apps and Progressive Web Apps.', status: 'a ver', logo:'kappa')
Company.create(name: 'Grama', description: 'Sofware house from Coimbra, Portugal. Our focus is software development, UI/​UX, technical design, quality assurance and project management.', status: 'a ver', logo:'kappa')
Company.create(name: 'Pink Room', description: 'Delivering your Android and iOS mobile apps faster and more cost-effectively.', status: 'a ver', logo:'kappa')
Company.create(name: 'psand', description: 'Specialists in bespoke content management systems that provide rock solid hosting & rock star support.', status: 'a ver', logo:'kappa')
Company.create(name: 'RedLight', description: 'We are a software development studio focusing on seamless communication and process transparency.', status: 'a ver', logo:'kappa')
Company.create(name: 'srgsoftware.io', description: '"No-shore" custom software development - on-shore quality with off-shore discounted rates with 30+ years of experience!', status: 'a ver', logo:'kappa')
Company.create(name: 'Versatil', description: 'A tua equipa de IT personalizada.', status: 'a ver', logo:'kappa')
